Icon/Mammoth/WebSupport/WebSupport/ViewModels/EventCreatorViewModel.cs
namespace WebSupport.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web.Mvc;
    using WebSupport.Models;

    public class EventCreatorViewModel
    {
        [Required]
        [DataType(DataType.MultilineText)]
        [RegularExpression(ValidationConstants.RegExForValidScanCode, ErrorMessage = ValidationConstants.ErrorMsgForInvalidScanCode)]
        public string ScanCodesText { get; set; }

        public SelectList AvailableRegions
        {
            get
            {
                return new SelectList(StaticData.WholeFoodsRegions);
            }
        }

        public string SelectedRegion { get; set; }

        public SelectList AvailableEventTypes
        {
            get
            {
                return new SelectList(StaticData.MammothEventTypes);
            }
        }

        public bool IsItemId { get; set; }
        public string SelectedEventType { get; set; }

        public List<string> Codes
        {
			get
			{
				return String.IsNullOrWhiteSpace(ScanCodesText)
					? new List<string>()
					: ScanCodesText.Replace(" ", String.Empty)
						.Split(new string[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries)
                        .Distinct().ToList();
			}
        }
    }
}

Icon/Mammoth/WebSupport/WebSupport/Controllers/EventCreatorController.cs
namespace WebSupport.Controllers
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Web.Mvc;
	using Icon.Common.DataAccess;
	using Icon.Logging;
	using WebSupport.DataAccess.Commands;
	using WebSupport.ViewModels;
	using DataAccess.Queries;

	public class EventCreatorController : Controller
	{
		#region Constants

		private const string CommandSuccessMessage = "Item events have been created successfully for reprocessing.";
		private const string FailedMessage = "An error has occured, please check the logs.";
		private const string InvalidScanCodesMessage = "The following scan codes do not exist: ";

		#endregion

		#region Fields

		private ILogger logger;
		private ICommandHandler<CreateEventsForRegionCommand> commandHandler;
		private IQueryHandler<GetExistingScanCodesParameters, List<string>> searchHandler;
		private IQueryHandler<GetItemIdsToScanCodesParameters, List<string>> searchScanCodes;

		#endregion

		#region Ctors

		public EventCreatorController(
			ILogger logger,
			ICommandHandler<CreateEventsForRegionCommand> commandHandler,
			IQueryHandler<GetExistingScanCodesParameters, List<string>> searchHandler,
			IQueryHandler<GetItemIdsToScanCodesParameters, List<string>> searchScanCodes)
		{
			this.logger = logger;
			this.commandHandler = commandHandler;
			this.searchHandler = searchHandler;
			this.searchScanCodes = searchScanCodes;
		}

		#endregion

		#region Public Methods

		// GET: EventCreator
		public ActionResult Index()
		{
			return View(new EventCreatorViewModel());
		}

		public ActionResult CreateEvents(EventCreatorViewModel viewModel)
		{
			if(!ModelState.IsValid)
			{
				return View("Index", viewModel);
			}

			var areScanCodesValid = this.ValidateScanCodesExist(viewModel);

			if(areScanCodesValid)
			{
				this.ExecuteCreateEvents(viewModel);
			}

			return View("Index", viewModel);
		}
		#endregion

		#region Private Methods
		private bool ValidateScanCodesExist(EventCreatorViewModel viewModel)
		{
			var queryResultMessage = string.Empty;
			bool areScanCodesValid = false;
			var codes = viewModel.Codes;

			try
			{
				if(viewModel.IsItemId)
				{
					codes = searchScanCodes.Search(new GetItemIdsToScanCodesParameters { Region = viewModel.SelectedRegion, ItemIds = codes });
					viewModel.ScanCodesText = String.Join(Environment.NewLine, codes);
				}

				var queryResult = this.searchHandler.Search(new GetExistingScanCodesParameters
				{
					Region = viewModel.SelectedRegion,
					ScanCodes = codes
				});

				areScanCodesValid = !queryResult.Any();
				if(!areScanCodesValid)
				{
					queryResultMessage = InvalidScanCodesMessage + string.Join(", ", queryResult);
				}
			}
			catch(Exception e)
			{
				queryResultMessage = FailedMessage;
				this.logger.Error(e.ToString());
			}
			finally
			{
				ViewBag.CommandResultMessage = queryResultMessage;
			}

			if (!areScanCodesValid)
				ViewBag.Error = true;

			return areScanCodesValid;
		}

		private void ExecuteCreateEvents(EventCreatorViewModel viewModel)
		{
			var commandResult = CommandSuccessMessage;

			try
			{
				this.commandHandler.Execute(new CreateEventsForRegionCommand
				{
					EventType = viewModel.SelectedEventType,
					Region = viewModel.SelectedRegion,
					ScanCodes = viewModel.Codes
				});
			}
			catch (Exception e)
			{
				commandResult = FailedMessage;
				this.logger.Error(e.ToString());
				ViewBag.Error = true;
			}
			finally
			{
				ViewBag.CommandResultMessage = commandResult;
			}
		}
		#endregion
	}
}

Icon/Mammoth/WebSupport/WebSupport/Views/EventCreator/Index.cshtml
@using WebSupport.Helpers
@model WebSupport.ViewModels.EventCreatorViewModel

@{
    ViewBag.Title = "Create Mammoth Events";
}
<h3 class="text-center">@ViewBag.Title</h3>

<div id="searchOptions">
    <div class="row container-fluid">
        @using (Html.BeginForm("CreateEvents", "EventCreator", null, FormMethod.Post, new { @class = "begin-form col-md-12" }))
        {
            <fieldset>
                <div class="row">
                    @Html.Label("Region", new { @class = "form-label col-md-4" })
                    <div>
                        @Html.DropDownListFor(model => model.SelectedRegion, Model.AvailableRegions, null, new { @class = "form-label col-md-8" })
                    </div>
                </div>

                <div class="row">
                    @Html.Label("Event Type", new { @class = "form-label col-md-4" })
                    <div>
                       @Html.DropDownListFor(model => model.SelectedEventType, Model.AvailableEventTypes, null, new { @class = "form-label col-md-8" })
                    </div>
                </div>

               <div class="row">
                   @Html.Label("Scan Code(s) or Item ID(s) (one per line)", new { id = "lblID", @class = "form-label col-md-4" })
                   <div class="radio-inline"><label>@Html.RadioButtonFor(m => m.IsItemId, "false") Scan Codes </label></div>
                   <div class="radio-inline"><label>@Html.RadioButtonFor(m => m.IsItemId, "true") Item IDs </label></div>
               </div>

               <div class="row">
                    <div class="form-input col- col-lg-offset-4">
                        @Html.TextAreaFor(model => Model.ScanCodesText, 20, 20, new { @class = "form-input col-md-8" })
                        @Html.ValidationMessageFor(model => Model.ScanCodesText, null, new { @class = "col-md-8 form-property-val" })
                    </div>
                </div>
            </fieldset>

            <div class="row">
                <div style="margin: 5px 0px">
                    <input type="submit" value="Submit" class="btn btn-default form-submit col-md-offset-4" id="search-button" />
                </div>
            </div>
        }
    </div>

    <div>
        @if (ViewBag.CommandResultMessage != null)
        {
            <div id="createItemAlert" class="@BootstrapAlertHelper.AlertClass(ViewBag.Error)">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>@ViewBag.CommandResultMessage</strong>
            </div>        
        }
    </div>

</div>