Icon/Demo/PriceManagement/PriceManagement/Models/ItemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PriceManagement.Models
{
    public class ItemModel
    {
        public ItemModel()
        {
            Prices = new List<PriceModel>();
        }

        public int ItemId { get; set; }
        public string ScanCode { get; set; }
        public List<PriceModel> Prices { get; set; }
    }
}

Icon/Demo/PriceManagement/PriceManagement/Models/LocaleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PriceManagement.Models
{
    public class LocaleModel
    {
        public int LocaleId { get; set; }
        public string LocaleName { get; set; }
        public int BusinessUnitId { get; set; }
        public string RegionCode { get; set; }
    }
}

Icon/Demo/PriceManagement/PriceManagement/Models/PriceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PriceManagement.Models
{
    public class PriceModel
    {
        public decimal Price { get; set; }
        public int ItemId { get; set; }
        public string Region { get; set; }
        public int BusinessUnit { get; set; }
    }
}

Icon/Demo/PriceManagement/PriceManagement/Models/RegionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PriceManagement.Models
{
    public class RegionModel
    {
        public string RegionCode { get; set; }
    }
}

Icon/Demo/PriceManagement/PriceManagement/ViewModels/ItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PriceManagement.ViewModels
{
    public class ItemViewModel
    {
        public int ItemId { get; set; }
        public string ScanCode { get; set; }
    }
}

Icon/Demo/PriceManagement/PriceManagement/ViewModels/PriceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PriceManagement.ViewModels
{
    public class PriceViewModel
    {

    }
}

Icon/Demo/PriceManagement/PriceManagement/ViewModels/RegionsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PriceManagement.ViewModels
{
    public static class RegionsViewModel
    {
        public static List<SelectListItem> All = new List<SelectListItem>
        {
            new SelectListItem { Text = "FL", Value = "FL" },
            new SelectListItem { Text = "MA", Value = "MA" },
            new SelectListItem { Text = "MW", Value = "MW" },
            new SelectListItem { Text = "NA", Value = "NA" },
            new SelectListItem { Text = "NC", Value = "NC" },
            new SelectListItem { Text = "NE", Value = "NE" },
            new SelectListItem { Text = "PN", Value = "PN" },
            new SelectListItem { Text = "RM", Value = "RM" },
            new SelectListItem { Text = "SO", Value = "SO" },
            new SelectListItem { Text = "SP", Value = "SP" },
            new SelectListItem { Text = "SW", Value = "SW" },
            new SelectListItem { Text = "UK", Value = "UK" }
        };
    }
}

Icon/Demo/PriceManagement/PriceManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PriceManagement.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Icon/Demo/PriceManagement/PriceManagement/Controllers/PriceController.cs
using PriceManagement.DataAccess;
using PriceManagement.Extensions;
using PriceManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PriceManagement.Controllers
{
    public class PriceController : Controller
    {
        IRepository repository;
        
        public PriceController()
        {
            this.repository = new Repository();
        }
        
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(string scanCodes)
        {
            var scanCodeList = scanCodes.Split('\n').Select(sc => sc.Trim());

            var items = repository.Items.Where(i => scanCodeList.Contains(i.ScanCode));

            return View(items.ToViewModels());
        }

        public ActionResult GetPricesForRegion(string regionCode, int itemId)
        {
            var locales = repository.Locales.Where(l => l.RegionCode == regionCode);

        }

        [HttpPost]
        public ActionResult Save(List<PriceModel> prices)
        {
            repository.AddRange(prices);

            return Json(new { Success = true });
        }
    }
}

Icon/Demo/PriceManagement/PriceManagement/Views/Price/Index.cshtml
@{
    ViewBag.Title = "Prices";
}

<h2>Price Search</h2>

@using (Html.BeginForm("Search", "Price", FormMethod.Post))
{
    @Html.TextArea("scanCodes");

    <input type="submit" value="Search"/>
}

Icon/Demo/PriceManagement/PriceManagement/Views/Price/Search.cshtml
@model IEnumerable<PriceManagement.ViewModels.ItemViewModel>
@using PriceManagement.ViewModels

@{
    ViewBag.Title = "Search";
}

@section Scripts
{
    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>
    <script src="~/Scripts/Price/price_edit.js"></script>
}

<h2>Search</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ScanCode)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ScanCode)
        </td>
        <td>
            <button data-itemId>Edit Prices</button>
            @*@Html.ActionLink( "Add Prices", "Edit", new { /* id=item.PrimaryKey */ }) |*@
        </td>
    </tr>
}

</table>

<div id="dialog">
    @Html.DropDownList("regions", RegionsViewModel.All, "Select a Region", null)
</div>