OutOfStock/Remove.Linked.Servers/OutOfStock/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.IO;
//using MassTransit;
using OOS.Model;
using OutOfStock.Models;


namespace OutOfStock.Controllers
{
    public class UploadController : Controller
    {
        public const string uploadFolder = "~/App_Data/UploadedFiles/";
        public static HashSet<string> supportedExtensions = 
            new HashSet<string>() { ".xls", ".xlsx", ".txt", ".csv" };

        //private ProductStatusToKnownUploadCommandMapper productStatusToKnownUploadCommandMapper;
        //private IServiceBus bus;

        //public UploadController(ProductStatusToKnownUploadCommandMapper productStatusToKnownUploadCommandMapper)
        public UploadController()
        {
           // this.productStatusToKnownUploadCommandMapper = productStatusToKnownUploadCommandMapper;
            
        }

        public ActionResult Index()
        {
           // OutOfStock.MvcApplication.oosLog.Trace("Enter");
            ActionResult result = null;

            if (!OOSUser.HasValidLocationInformation)
            {
                result = View("~/Views/Shared/InvalidLocationInformation.cshtml");
            }
            else
            {
                if (!OOSUser.isRegionalBuyer)
                    result = new RedirectResult("~/Home/Index");
                else
                    result = View();
            }
        
            //OutOfStock.MvcApplication.oosLog.Trace("Exit");
            return result;
        }

        [HttpPost]
        public ActionResult ReadExcelSheet(HttpPostedFileBase file)
        {
            //OutOfStock.MvcApplication.oosLog.Trace("Enter");
            ActionResult result = null;
            var msg = string.Empty;
            try
            {
                var serverFilename = string.Empty;
                var userFileName = string.Empty;
                var errorMessage = string.Empty;
                var sheetErrors = new List<string>();
                var isError = (file == null || file.ContentLength <= 0 || string.IsNullOrWhiteSpace(file.FileName));
                if (isError)
                    errorMessage = "Please choose a file to upload.";
                else
                {
                    string ext = Path.GetExtension(file.FileName);
                    isError = !supportedExtensions.Contains(ext);
                    if (isError)
                        errorMessage = string.Format("Unsupported file extension: {0}", ext);
                    else
                    {
                        userFileName = Path.GetFileName(file.FileName);
                        serverFilename = HttpContext.Server.MapPath(uploadFolder) +
                            Guid.NewGuid().ToString() + ext;
                        try
                        {
                            file.SaveAs(serverFilename);
                        }
                        catch (Exception ex)
                        {
                            OutOfStock.MvcApplication.oosLog.Warn(ex.Message + ", Stack=" + ex.StackTrace);
                            isError = true;
                            errorMessage = string.Format("Internal error uploading file. ({0})", ex.Message);
                        }
                    }
                }
                int recordsUpdated = 0;
                if (!isError)
                {

                    if (string.IsNullOrEmpty(OOSUser.userRegion))
                    {
                        msg = "";
                        userFileName = "";
                        errorMessage = "Unable to determine the region the user belongs to.";
                        OutOfStock.MvcApplication.oosLog.Warn(errorMessage);
                    }
                    else if (OOSUser.userRegion.ToUpper() == "CE")
                    {
                        msg = "";
                        userFileName = "";
                        errorMessage = "Only regional users can upload data for their region.";
                        OutOfStock.MvcApplication.oosLog.Warn(errorMessage);
                    }

                    else
                    {
                        try
                        {
                            //sheetErrors = OutOfStock.Models.KnownOOSUploadModel.ReadExcelFile(serverFilename, productStatusToKnownUploadCommandMapper, bus);
                            sheetErrors = OutOfStock.Models.KnownOOSUploadModel.ReadExcelFile(serverFilename,
                                                                                              out recordsUpdated);
                        }
                        catch (Exception ex)
                        {
                            OutOfStock.MvcApplication.oosLog.Warn(ex.Message + ", Stack=" + ex.StackTrace);
                            errorMessage = "There was an error while interpreting the file";
                        }
                    }
                }
                if (!string.IsNullOrWhiteSpace(serverFilename))
                {
                    for (int retry = 0; retry < 10; ++retry)
                    {
                        try
                        {
                            System.IO.File.Delete(serverFilename);
                            retry = 10;
                        }
                        catch (Exception)
                        {
                            System.Threading.Thread.Sleep(200);
                        }
                    }
                }
                ViewBag.sheetErrors = sheetErrors;
                
                if ( ! string.IsNullOrEmpty(userFileName))
                {
                    ViewBag.MessageClass = "list_good";
                    msg= string.Format("[{0}] was uploaded. ", userFileName);
                }

                if (sheetErrors.Count > 0)
                {
                    ViewBag.MessageClass = "list_bad";
                    msg = string.Format("[{0}] was uploaded but some rows had errors. ", userFileName);
                }

                if (errorMessage.Length > 0)
                    msg +=  errorMessage;
                else
                {

                    if ( recordsUpdated == 1)
                    {
                        msg += string.Format("{0} record was saved.", recordsUpdated);
                    }
                    else
                    {
                        msg += string.Format("{0} records were saved.", recordsUpdated);
                    }
                }

                ViewBag.Message = msg;
                result = View("Index");
            }
            catch (Exception ex)
            {
                OutOfStock.MvcApplication.oosLog.Warn(ex.Message + ", Stack=" + ex.StackTrace);
                ViewBag.Message = "Sorry, an internal error has occurred.";
                result = View("Index");
            }
            //OutOfStock.MvcApplication.oosLog.Trace("Exit");
            return result;
        }

    }
}

OutOfStock/Remove.Linked.Servers/OutOfStock/Views/Upload/Index.cshtml
@model OutOfStock.Models.KnownOOSUploadModel
@{
    ViewBag.Title = "Upload OOS files";
}

@(Html.Telerik().ScriptRegistrar().OnDocumentReady(@<text>

    $('#file').first().focus();

</text>))


<table class="CleanTable" style="width:auto;">
    <tr class="CleanTable">
        <td align="left" valign="top" class="CleanTable" style="width:240px;">
            <h2>UPLOAD OUT OF<br />STOCK FILES</h2>
            <p>Choose a file to upload.</p>
        </td>
        <td align="left" valign="top" class="CleanTable">

    @using (Html.BeginForm("ReadExcelSheet", "Upload", FormMethod.Post, new { defaultbutton = "Upload", enctype = "multipart/form-data", id="UpSubmit" }))
    {   
        <div class="InfoPanel" style="text-align: center;">
            <p style="font-size: 1em;">Upload product statuses using an Excel spreadsheet. The columns shown below are required. Use this <a href="/Content/OOSUploadTemplate.xlsx?v=1.1.0.0">template</a> to get started.</p>
            <img src="/Content/images/exceltemplate.png" alt="template"/>
            <table align="center">
                <tr>
                    <td align="left" valign="top" style="padding-right:28px;">
                        <input type="file" name="file" id="file" tabindex="1" />
                    </td> 
                    <td align="left" valign="top" style="padding-left:32px;">
                        <input type="submit" value="&nbsp;&nbsp;Upload&nbsp;&nbsp;" name="Upload" id="Upload" tabindex="2" />
                    </td>
                </tr>
            </table>
        
           
        </div>
        
        if (ViewBag.Message != null)
            {
                <div>
                    <ul id="sortablelist">

                        @if (ViewBag.Message != null)
                        {
                            <li class="@ViewBag.MessageClass">@ViewBag.Message</li> 
                        }
                        @foreach (string message in ViewBag.SheetErrors)
                        {
                            <li class="list_item">@message.Trim()</li> 
                        }
                    </ul>
                </div>
            }
        
    }
        
        </td>
    </tr>
</table>


@section HeadContent   
{
    <style type="text/css">

        #sortablelist {
            font: 11px Arial, Helvetica, sans-serif;
            line-height: 16px;
            padding: 5px;
        }

        #sortablelist li.list_good {
            background: url("/Content/images/icon_small_check.gif") 0 0 no-repeat;
            list-style: none;
            padding-left: 20px;
               
        }
       
        #sortablelist li.list_bad { 
            background: url("/Content/images/dialog-close.png") 0 0 no-repeat;
            list-style: none;
            padding-left: 20px;

        }
        #sortablelist li.list_item { 
            list-style: none;
            padding-left: 40px;
            padding-top: 5px;

        }

    </style>
    