Icon/Web/Icon.Web.Mvc/Models/HierarchyViewModel.cs
using Icon.Web.DataAccess.Models;

namespace Icon.Web.Mvc.Models
{
    public class HierarchyViewModel
    {
        public int HierarchyId { get; set; }
        public string HierarchyName { get; set; }

        public HierarchyViewModel(HierarchyModel model)
        {
            this.HierarchyId = model.HierarchyId;
            this.HierarchyName = model.HierarchyName;
        }
    }
}

Icon/Web/Icon.Web.Mvc/Models/ItemHistory/Infor/Brand.cs
using Newtonsoft.Json;

namespace Icon.Web.Mvc.Models
{
    public class Brand
    {
        [JsonProperty("Brand ID")]
        public string BrandId { get; set; }
        [JsonProperty("Brand Name")]
        public string BrandName { get; set; }
        [JsonProperty("Brand Abbreviation")]
        public string BrandAbbreviation { get; set; }

    }
}

Icon/Web/Icon.Web.Mvc/Controllers/HierarchyController.cs
using DevTrends.MvcDonutCaching;
using Icon.Common.DataAccess;
using Icon.Framework;
using Icon.Logging;
using Icon.Web.Common;
using Icon.Web.DataAccess.Models;
using Icon.Web.DataAccess.Queries;
using Icon.Web.Mvc.Extensions;
using Icon.Web.Mvc.Models;
using Icon.Web.Mvc.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;

namespace Icon.Web.Controllers
{
    public class HierarchyController : Controller
    {
        private ILogger logger;
        private IconWebAppSettings settings;
        private IQueryHandler<GetHierarchyParameters, List<Hierarchy>> getHierarchyQuery;
        private IQueryHandler<GetHierarchiesParameters, IEnumerable<HierarchyModel>> getHierarchiesQueryHandler;

        public HierarchyController(
            ILogger logger,
            IconWebAppSettings settings,
            IQueryHandler<GetHierarchyParameters, List<Hierarchy>> getHierarchyQuery,
            IQueryHandler<GetHierarchiesParameters, IEnumerable<HierarchyModel>> getHierarchiesQueryHandler)
        {
            this.settings = settings;
            this.logger = logger;
            this.getHierarchyQuery = getHierarchyQuery;
            this.getHierarchiesQueryHandler = getHierarchiesQueryHandler;
        }

        // GET: /Hierarchy/
        public ActionResult Index(HierarchySearchViewModel viewModel)
        {
            int selectedHierarchyId = viewModel.SelectedHierarchyId;

            //These two Hierarchies should no longer be accessible by ANYONE
            switch(selectedHierarchyId)
            {
                case Hierarchies.Browsing:
                case Hierarchies.CertificationAgencyManagement:
                    return View("AccessDenied");
            }

            HierarchySearchViewModel hierarchySearchViewModel = new HierarchySearchViewModel();

            hierarchySearchViewModel.Hierarchies = PopulateHierarchySelectList();
            hierarchySearchViewModel.SelectedHierarchyId = selectedHierarchyId;
            hierarchySearchViewModel.UserWriteAccess = this.GetWriteAccess();
            return View(hierarchySearchViewModel);
        }

        // GET: /Hierarchy/Search
        [DonutOutputCache(Duration=1, VaryByParam = "*")]
        public PartialViewResult Search(HierarchySearchViewModel viewModel)
        {
            try
            {
                // Set up a search object and execute the query.
                GetHierarchyParameters searchHierarchyParameters = new GetHierarchyParameters
                {
                    HierarchyId = viewModel.SelectedHierarchyId,
                    IncludeNavigation = true
                };

                viewModel.Hierarchy = getHierarchyQuery.Search(searchHierarchyParameters).Single();

                var financialHierarchyClasses = getHierarchyQuery.Search(new GetHierarchyParameters
                {
                    HierarchyId = Hierarchies.Financial
                }).Single();

                var hierarchyClasses = viewModel.Hierarchy.HierarchyClass
                    .Select(hc => new HierarchyClassGridViewModel
                    {
                        HierarchyClassId = hc.hierarchyClassID,
                        HierarchyClassName = hc.hierarchyClassName,
                        HierarchyParentClassId = hc.hierarchyParentClassID,
                        TaxAbbreviation = HierarchyClassAccessor.GetTaxAbbreviation(hc),
                        TaxRomance = HierarchyClassAccessor.GetTaxRomance(hc),
                        SubTeam = HierarchyClassAccessor.MapSubTeamTraitIdToValue(hc, financialHierarchyClasses.HierarchyClass.ToList()),
                        NonMerchandiseTrait = HierarchyClassAccessor.GetNonMerchandiseTrait(hc),
                        SubBrickCode = HierarchyClassAccessor.GetSubBrickCode(hc),
                        AddNodeLink = $"<a href=\"../HierarchyClass/Create?parentId={hc.hierarchyClassID}&hierarchyId={hc.hierarchyID}\">Add Child</a>",
                        EditNodeLink = $"<a href=\"../HierarchyClass/Edit?hierarchyClassId={hc.hierarchyClassID}\">Edit</a>",
                        DeleteNodeLink = $"<a href=\"../HierarchyClass/Delete?hierarchyClassId={hc.hierarchyClassID}\">Delete</a>"
                    })
                    .OrderBy(hc => hc.HierarchyClassName)
                    .ToList();

                viewModel.HierarchyClasses = BuildHierarchyClassModelRecursive(hierarchyClasses, null).AsQueryable();
                viewModel.UserWriteAccess = this.GetWriteAccess();
                return PartialView("_HierarchyViewPartial", viewModel);
            }

            catch (Exception ex)
            {
                var exceptionLogger = new ExceptionLogger(logger);
                exceptionLogger.LogException(ex, this.GetType(), MethodBase.GetCurrentMethod());
                List<string> allErrors = new List<string>() { "Error in getting data." };
                ViewData["ErrorMessages"] = allErrors;
                return PartialView("_HierarchyViewPartial", viewModel);
            }
        }

        private List<HierarchyClassGridViewModel> BuildHierarchyClassModelRecursive(List<HierarchyClassGridViewModel> allHierarchyClasses, HierarchyClassGridViewModel parentHierarchyClass)
        {
            int? hierarchyParentClassId = null;

            if (parentHierarchyClass != null)
            {
                hierarchyParentClassId = parentHierarchyClass.HierarchyClassId;
            }

            var childHierarchyClasses = allHierarchyClasses.Where(e => e.HierarchyParentClassId == hierarchyParentClassId).ToList();

            // If all classes are top-level classes, then there are no children to traverse.  Return the list of hierarchy classes.
            if (childHierarchyClasses.Count == allHierarchyClasses.Count)
            {
                return allHierarchyClasses;
            }

            List<HierarchyClassGridViewModel> hierarchyClasses = new List<HierarchyClassGridViewModel>();

            foreach (var hc in childHierarchyClasses)
            {
                hierarchyClasses.Add(new HierarchyClassGridViewModel()
                {
                    HierarchyClassId = hc.HierarchyClassId,
                    HierarchyParentClassId = hc.HierarchyParentClassId,
                    HierarchyClassName = hc.HierarchyClassName,
                    TaxAbbreviation = hc.TaxAbbreviation,
                    SubTeam = hc.SubTeam,
                    NonMerchandiseTrait = hc.NonMerchandiseTrait,
                    SubBrickCode = hc.SubBrickCode,
                    AddNodeLink = hc.AddNodeLink,
                    EditNodeLink = hc.EditNodeLink,
                    DeleteNodeLink = hc.DeleteNodeLink,
                    HierarchySubClasses = BuildHierarchyClassModelRecursive(allHierarchyClasses, hc)
                });
            }

            return hierarchyClasses;
        }

        private IEnumerable<SelectListItem> PopulateHierarchySelectList()
        {
            var hierarchies = getHierarchyQuery.Search(new GetHierarchyParameters { IncludeNavigation = false });

            var dropDownList = hierarchies
                .Where(h => h.hierarchyID != Hierarchies.Financial
                    && h.hierarchyID != Hierarchies.Brands
                    && h.hierarchyID != Hierarchies.National
                    && h.hierarchyID != Hierarchies.CertificationAgencyManagement
                    && h.hierarchyID != Hierarchies.Browsing)
                .Select(h => new DropDownViewModel
                {
                    Id = h.hierarchyID,
                    Name = h.hierarchyName
                });

            return dropDownList.ToSelectListItem();
        }

        [HttpGet]
        [DonutOutputCache(Duration = 3600, Location = System.Web.UI.OutputCacheLocation.Server, VaryByParam = "")]
        public ActionResult All()
        {
            var hierarchies = getHierarchiesQueryHandler.Search(new GetHierarchiesParameters())
                .Select(h => new HierarchyViewModel(h));
            return Json(hierarchies, JsonRequestBehavior.AllowGet);
        }

        private Enums.WriteAccess GetWriteAccess()
        {
            try
            {
                bool hasWriteAccess = this.settings.WriteAccessGroups.Split(',').Any(x => this.HttpContext.User.IsInRole(x.Trim()));
                var userAccess = Enums.WriteAccess.None;

                if (hasWriteAccess)
                {
                    userAccess = Enums.WriteAccess.Full;
                }

                return userAccess;
            }
            catch
            {
                return Enums.WriteAccess.None;
            }
        }
    }
}

Icon/Web/Icon.Web.Mvc/Controllers/RefreshDataController.cs
using Icon.Common.DataAccess;
using Icon.Common.Models;
using Icon.Logging;
using Icon.Web.DataAccess.Commands;
using Icon.Web.DataAccess.Queries;
using Icon.Web.Mvc.Attributes;
using Icon.Web.Mvc.Extensions;
using Icon.Web.Mvc.Models.RefreshData;
using Icon.Web.Mvc.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Icon.Web.Mvc.Controllers
{
    [AdminAccessAuthorizeAttribute]
    public class RefreshDataController : Controller
    {
        private ICommandHandler<PublishItemUpdatesCommand> publishItemUpdatesCommandHandler;
        private ICommandHandler<RefreshLocalesCommand> addLocaleMessagesCommandHandler;
        private ICommandHandler<RefreshHierarchiesCommand> refreshHierarchiesCommandHandler;
        private ICommandHandler<RefreshAttributesCommand> publishAttributeQueueCommandHandler;
        private IQueryHandler<GetAttributeByAttributeIdParameters, AttributeModel> getAttributeByAttributeIdQuery;
        private ILogger logger;
        private IconWebAppSettings settings;

        public RefreshDataController(ICommandHandler<PublishItemUpdatesCommand> publishItemUpdatesCommandHandler,
            ICommandHandler<RefreshLocalesCommand> addLocaleMessagesCommandHandler,
            ICommandHandler<RefreshHierarchiesCommand> refreshHierarchiesCommandHandler,
            ICommandHandler<RefreshAttributesCommand> publishAttributeQueueCommandHandler,
            IQueryHandler<GetAttributeByAttributeIdParameters, AttributeModel> getAttributeByAttributeIdQuery,
            ILogger logger,
            IconWebAppSettings settings)
        {
            this.publishItemUpdatesCommandHandler = publishItemUpdatesCommandHandler;
            this.addLocaleMessagesCommandHandler = addLocaleMessagesCommandHandler;
            this.refreshHierarchiesCommandHandler = refreshHierarchiesCommandHandler;
            this.publishAttributeQueueCommandHandler = publishAttributeQueueCommandHandler;
            this.getAttributeByAttributeIdQuery = getAttributeByAttributeIdQuery;
            this.logger = logger;
            this.settings = settings;

        }

        // GET: RefreshData
        public ActionResult Items()
        {
            return View(new RefreshDataViewModel());
        }

        [HttpPost]
        public ActionResult Items(RefreshDataViewModel viewModel)
        {
            try
            {
                if (viewModel == null || String.IsNullOrWhiteSpace(viewModel.Identifiers))
                {
                    return View(viewModel);
                }

                string[] parsedScanCodes = viewModel.Identifiers.ParseByLine();
                string[] tooLongScanCodes = parsedScanCodes.Where(sc => sc.Length > 13).ToArray();
                string[] validScanCodes = parsedScanCodes.Except(tooLongScanCodes).ToArray();

                string[] uniqueScanCodes = validScanCodes.Distinct().ToArray();
                string[] uniqueScanCodesWithNoWhitespaceLines = uniqueScanCodes.Where(sc => !String.IsNullOrWhiteSpace(sc)).ToArray();
                List<string> scanCodesToRefresh = uniqueScanCodesWithNoWhitespaceLines.Take(3000).ToList();

                publishItemUpdatesCommandHandler.Execute(new PublishItemUpdatesCommand { ScanCodes = scanCodesToRefresh });
            }
            catch (Exception ex)
            {
                logger.Error(ex.ToString());
                ViewBag.Message = "Unexpected exception occurred: " + ex.Message;
                return View(viewModel);
            }
            ViewBag.Message = "Refreshed items successfully.";
            return View(new RefreshDataViewModel());
        }

        public ActionResult Attributes()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Attributes(RefreshAttributesViewModel viewModel)
        {
            try
            {
                if (viewModel == null || String.IsNullOrWhiteSpace(viewModel.AttributeIds))
                {
                    return View(viewModel);
                }

                string[] parsedIds = viewModel.AttributeIds.ParseByLine();

                string[] uniqueIds = parsedIds.Distinct().ToArray();
                string[] uniqueIdsWithNoWhitespaceLines = uniqueIds.Where(sc => !String.IsNullOrWhiteSpace(sc)).ToArray();
                List<string> attributeIdsToRefresh = uniqueIdsWithNoWhitespaceLines.Take(3000).ToList();

                List<string> badIds = new List<string>();
                foreach (var id in attributeIdsToRefresh)
                {
                    int idInt;
                    if(!int.TryParse(id, out idInt))
                    {
                        badIds.Add(id);
                    }
                    else
                    {
                        var attribute = this.getAttributeByAttributeIdQuery.Search(new GetAttributeByAttributeIdParameters() { AttributeId = idInt });
                        if (attribute == null)
                        {
                            badIds.Add(id);
                        }
                    }
                }

                if(badIds.Count > 0)
                {
                    string concat = string.Join(", ", badIds.ToArray());
                    ViewBag.Message = $"The following IDs are invalid: {concat}";
                    return View(viewModel);
                }

                publishAttributeQueueCommandHandler.Execute(new RefreshAttributesCommand { AttributeIds = attributeIdsToRefresh });
            }
            catch (Exception ex)
            {
                logger.Error(ex.ToString());
                ViewBag.Message = "Unexpected exception occurred: " + ex.Message;
                return View(viewModel);
            }
            ViewBag.Message = "Refreshed attributes successfully.";
            return View(new RefreshAttributesViewModel());
        }

        public ActionResult Locales()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Locales(RefreshDataViewModel viewModel)
        {
            try
            {
                if (viewModel == null || string.IsNullOrWhiteSpace(viewModel.Identifiers))
                {
                    return View(viewModel);
                }

                List<int> localeIdsToRefresh = viewModel.Identifiers.ParseByLine()
                    .Take(3000)
                    .Select(id => int.Parse(id))
                    .ToList();

                addLocaleMessagesCommandHandler.Execute(new RefreshLocalesCommand { LocaleIds = localeIdsToRefresh });
            }
            catch (Exception ex)
            {
                logger.Error(ex.ToString());
                ViewBag.Message = "Unexpected exception occurred: " + ex.Message;
                return View(viewModel);
            }
            ViewBag.Message = "Refreshed Locales successfully.";
            return View(new RefreshDataViewModel());
        }

        public ActionResult Hierarchy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Hierarchy(RefreshDataViewModel viewModel)
        {
            try
            {
                if (viewModel == null || string.IsNullOrWhiteSpace(viewModel.Identifiers))
                {
                    return View(viewModel);
                }

                List<int> hierarchyClassIds = viewModel.Identifiers.ParseByLine()
                    .Take(3000)
                    .Select(id => int.Parse(id))
                    .ToList();

                refreshHierarchiesCommandHandler.Execute(new RefreshHierarchiesCommand
                {
                    HierarchyClassIds = hierarchyClassIds,
                    IsManufacturerHierarchyMessage =settings.IsManufacturerHierarchyMessage
                });
            }
            catch (Exception ex)
            {
                logger.Error(ex.ToString());
                ViewBag.Message = "Unexpected exception occurred: " + ex.Message;
                return View(viewModel);
            }

            ViewBag.Message = "Refreshed Hierarchy successfully.";
            return View(new RefreshDataViewModel());
        }
    }
}

Icon/Web/Icon.Web.Mvc/Views/RefreshData/Attributes.cshtml
@model Icon.Web.Mvc.Models.RefreshData.RefreshAttributesViewModel

@{
    ViewBag.Title = "Refresh Attributes";
}

    <h2>Refresh Attributes</h2>


<div id="searchOptions" class="page-section">
        @using (Html.BeginForm("Attributes", "RefreshData", FormMethod.Post))
        {
            <div class="form-group">
                @Html.Label(String.Format("Attribute IDs (one per line, maximum {0})", 3000), new { @class = "form-label" })
                @Html.TextAreaFor(model => Model.AttributeIds, 15, 13, new { @class = "form-control form-input", @type = "number" })
                @Html.ValidationMessageFor(model => model.AttributeIds, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Refresh" class="btn btn-light form-submit" id="refresh-button" />
            </div>
        }
    @if (ViewBag.Message != null)
    {
        <div>
            <p>@ViewBag.Message</p>
        </div>
    }
</div>

Icon/Web/Icon.Web.Mvc/Views/RefreshData/Brands.cshtml
@model Icon.Web.Mvc.Models.RefreshData.RefreshDataViewModel

@{
    ViewBag.Title = "Refresh Brands";
}

<h2>Refresh Brands</h2>


<div id="searchOptions" class="page-section">
    @using (Html.BeginForm("Brands", "RefreshData", FormMethod.Post))
    {
        <div class="form-group">
            @Html.Label(String.Format("Brand IDs (one per line, maximum {0})", 3000), new { @class = "form-label" })
            @Html.TextAreaFor(model => Model.Identifiers, 15, 13, new { @class = "form-control form-input", @type = "number" })
            @Html.ValidationMessageFor(model => model.Identifiers, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Refresh" class="btn btn-light form-submit" id="refresh-button" />
        </div>
    }
    @if (ViewBag.Message != null)
    {
        <div>
            <p>@ViewBag.Message</p>
        </div>
    }
</div>

Icon/Web/Icon.Web.Mvc/Views/RefreshData/Hierarchy.cshtml
@model Icon.Web.Mvc.Models.RefreshData.RefreshDataViewModel

@{
    ViewBag.Title = "Refresh Hierarchy";
}

<h2>Refresh Hierarchy</h2>


<div id="searchOptions" class="page-section">
    @using (Html.BeginForm("Hierarchy", "RefreshData", FormMethod.Post))
    {
    <div class="form-group">
        @Html.Label(String.Format("Hierarchy IDs (one per line, maximum {0})", 3000), new { @class = "form-label" })
        @Html.TextAreaFor(model => Model.Identifiers, 15, 13, new { @class = "form-control form-input", @type = "number" })
        @Html.ValidationMessageFor(model => model.Identifiers, "", new { @class = "text-danger" })
    </div>

        <div class="form-group">
            <input type="submit" value="Refresh" class="btn btn-light form-submit" id="refresh-button" />
        </div>
    }
    @if (ViewBag.Message != null)
    {
        <div>
            <p>@ViewBag.Message</p>
        </div>
    }
</div>

Icon/Web/Icon.Web.Mvc/Views/RefreshData/Items.cshtml
@model Icon.Web.Mvc.Models.RefreshData.RefreshDataViewModel

@{
    ViewBag.Title = "Refresh Items";
}

<h2>Refresh Items</h2>


<div id="searchOptions" class="page-section">
        @using (Html.BeginForm("Items", "RefreshData", FormMethod.Post))
        {
            <div class="form-group">
                @Html.Label(String.Format("Scan Codes (one per line, maximum {0})", 3000), new { @class = "form-label" })
                @Html.TextAreaFor(model => Model.Identifiers, 15, 13, new { @class = "form-control form-input", @type = "number" })
                @Html.ValidationMessageFor(model => model.Identifiers, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Refresh" class="btn btn-light form-submit" id="refresh-button" />
            </div>
        }
    @if (ViewBag.Message != null)
    {
        <div>
            <p>@ViewBag.Message</p>
        </div>
    }
</div>

Icon/Web/Icon.Web.Mvc/Views/RefreshData/Locales.cshtml
@model Icon.Web.Mvc.Models.RefreshData.RefreshDataViewModel

@{
    ViewBag.Title = "Refresh Locales";
}

    <h2>Refresh Locales</h2>


<div id="searchOptions" class="page-section">
        @using (Html.BeginForm("Locales", "RefreshData", FormMethod.Post))
        {
            <div class="form-group">
                @Html.Label(String.Format("Locale IDs (one per line, maximum {0})", 3000), new { @class = "form-label" })
                @Html.TextAreaFor(model => Model.Identifiers, 15, 13, new { @class = "form-control form-input", @type = "number" })
                @Html.ValidationMessageFor(model => model.Identifiers, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Refresh" class="btn btn-light form-submit" id="refresh-button" />
            </div>
        }
    </div>
    @if (ViewBag.Message != null)
    {
        <div>
            <p>@ViewBag.Message</p>
        </div>
    }

Icon/Web/Icon.Web.Mvc/Views/RefreshData/Merchandise.cshtml
@model Icon.Web.Mvc.Models.RefreshData.RefreshDataViewModel

@{
    ViewBag.Title = "Refresh Merchandise Hierarchy Classes";
}

<h2>Refresh Merchandise</h2>


<div id="searchOptions" class="page-section">
    @using (Html.BeginForm("Merchandise", "RefreshData", FormMethod.Post))
    {
        <div class="form-group">
            @Html.Label(String.Format("Merchandise Hierarchy Class IDs (one per line, maximum {0})", 3000), new { @class = "form-label" })
            @Html.TextAreaFor(model => Model.Identifiers, 15, 13, new { @class = "form-control form-input", @type = "number" })
            @Html.ValidationMessageFor(model => model.Identifiers, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Refresh" class="btn btn-light form-submit" id="refresh-button" />
        </div>
    }
    @if (ViewBag.Message != null)
    {
        <div>
            <p>@ViewBag.Message</p>
        </div>
    }
</div>